// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlqdLMLUW7Af0FMHiKnj8DscpqZeIaPWE',
    appId: '1:204283997752:ios:d3aec7cd9b3679771780cd',
    messagingSenderId: '204283997752',
    projectId: 'chatapp-391ac',
    storageBucket: 'chatapp-391ac.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QRIDv5G9QkYcxBVlMh3f-bB2XutIi5g',
    appId: '1:204283997752:web:b2556b79a768d43b1780cd',
    messagingSenderId: '204283997752',
    projectId: 'chatapp-391ac',
    authDomain: 'chatapp-391ac.firebaseapp.com',
    storageBucket: 'chatapp-391ac.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9QRIDv5G9QkYcxBVlMh3f-bB2XutIi5g',
    appId: '1:204283997752:web:b2556b79a768d43b1780cd',
    messagingSenderId: '204283997752',
    projectId: 'chatapp-391ac',
    authDomain: 'chatapp-391ac.firebaseapp.com',
    storageBucket: 'chatapp-391ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqdLMLUW7Af0FMHiKnj8DscpqZeIaPWE',
    appId: '1:204283997752:ios:d3aec7cd9b3679771780cd',
    messagingSenderId: '204283997752',
    projectId: 'chatapp-391ac',
    storageBucket: 'chatapp-391ac.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7BVDXq935YUMHE4h3G9jhmYUgYlDU1KI',
    appId: '1:204283997752:android:ada1a9b7b1bb10781780cd',
    messagingSenderId: '204283997752',
    projectId: 'chatapp-391ac',
    storageBucket: 'chatapp-391ac.appspot.com',
  );

}